Basic scaffolding

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,4 +1,7 @@
+sudo: false
 language: python
+virtualenv:
+  system_site_packages: false
 python:
 #  - "3.4"
 #  - "3.5"
@@ -9,8 +12,26 @@ python:
 #  - "nightly"  # nightly build
 # command to install dependencies
 install:
-  - make install
-# command to run tests
+  - pip install -r requirements.txt
+  # ^  DEPRECATION WARNING:
+  # The automatic creation of a `requirements.txt` file is deprecated.
+  # See `Dependency Management` in the docs for other options.
+before_script:
+  - git config --global user.email "you@example.com"
+  - git config --global user.name "Your Name"
 script:
-  - make test
-
+  - python setup.py develop
+  - tox
+  - |
+    if [[ "$COVERAGE" == "true" ]]; then
+      pre-commit install
+      pre-commit run --all-files
+    fi
+after_success:
+  - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
+after_script:
+  - travis-cleanup
+cache:
+  pip: true
+  directories:
+    - $HOME/miniconda
